### ISSUE TITLE
Make this available through composer

### ISSUE THREAD

**Issue by Reached** [QuickPay/quickpay-php-client#11]
Hi,
Would be great if this library was available through composer, so users could just require it in their composer.json file, is something like this in the pipeline?

Thank you!

**Comment by speedster-kiev** [comment]
While developers will be fixing this, you can try next code to install it through composer

    "require": {
        "QuickPay/quickpay-php-client": "*@dev"
    },
    "repositories": [
        {
            "type": "package",
            "package": {
                "name": "QuickPay/quickpay-php-client",
                "version": "dev-master",
                "dist": {
                    "url": "git://github.com/QuickPay/quickpay-php-client.git",
                    "type": "git"
                },
                "source": {
                    "url": "git://github.com/QuickPay/quickpay-php-client.git",
                    "type": "git",
                    "reference": "master"
                },
                "autoload": {
                    "classmap": ["QuickPay"]
                }
            }

        }
    ]

**Comment by lsolesen** [comment]
This has now been fixed and you can find it here: https://packagist.org/packages/quickpay/quickpay-php-client
