### ISSUE TITLE
Not authorized: Not authorized to GET /payments

### ISSUE THREAD

**Issue by JensKirk** [QuickPay/quickpay-php-client#12]
Hi

When I do a request with...
$result = $client->request->get("/payments/".$order->payment_transactionid);

... I get the transaction, but if I delete the last part of the line so it becomes...
$result = $client->request->get("/payments");

... then I get this error: 
Not authorized: Not authorized to GET /payments

I have not changed anything but this line.

How to I get all the transactions? And even better - how do I get a transaction when I do not know the transaction ID but I do know the order number?

(I have followed the guide on: https://github.com/QuickPay/quickpay-php-client )

**Comment by ta** [comment]
Please see the API docs at http://tech.quickpay.net/api/services/?scope=merchant#GET-payments---format-

Hint: `GET /payments?order_id=x`

**Comment by JensKirk** [comment]
Thank you :-)

I have changed the PHP code to:
$payments = $client->request->get("/payments?order_id=".$order->system_name."-".$order->order_id);

The request adresse becomes: /payments?order_id=VM-44

But it still gives the access error:

QuickPay\API\Response Object ( [status_code:protected] => 401 [sent_headers:protected] => GET /payments?order_id=VM-44 HTTP/1.1 Host: api.quickpay.net Accept-Version: v10 Accept: application/json Authorization: Basic OjYxYjEzYmMyMWY0MWNiMjY3NmJiMWVlNWFiZDdjOTYwMTI0ZTIzNzJhNmJjYzhlZWZiNmRmMjE1ZWZiY2NhYjI= [received_headers:protected] => HTTP/1.1 401 Unauthorized Content-Type: application/json Date: Sat, 25 Jul 2015 20:55:38 GMT Server: nginx Content-Length: 93 Connection: keep-alive [response_data:protected] => {"message":"Not authorized: Not authorized to GET /payments","errors":null,"error_code":null} )

**Comment by ta** [comment]
Ok, next step is to make sure that your user/agreement/api-key has the correct permissions. This is perhaps a more general support issue - please feel free to reach out to support@quickpay.net

**Comment by JensKirk** [comment]
I have written to them already. I do not understand why this line:
$result = $client->request->get("/payments/".$order->payment_transactionid);

Gives me the transaction as it should (it is working).

But changing the line to:
$result = $client->request->get("/payments?order_id=".$order->system_name."-".$order->order_id);

Gives me the access error.

**Comment by ta** [comment]
Every API endpoint can be allowed/disallowed for maximal control. Granting permission to X will not set other/implicit permissions on Y.

**Comment by JensKirk** [comment]
Where in Quickpay's new backend GUI do I give permissions? I cannot find such a setting.

If I cannot do this it is a bug in the Quickpay system. I am just following the code and guide on the frontpage of this github-quickpay-project.

Can you make a ... 
$result = $client->request->get("/payments");
... on your site?

**Comment by JensKirk** [comment]
I found this in the backend: Settings > Users > API user

Perhaps the setting is in there somewhere.

**Comment by JensKirk** [comment]
The point "See/create payments" had a tick in "Create" but not in "Show". I set a tick there too but the error still came up.

**Comment by JensKirk** [comment]
It is working now. It was because I used the API key for the payment window and not the API user so upgrading the permissions for the API did not have an effect (before changing the API key).

I see it as a bug that the API user does not have a tick in "View" for "See/create payments" for default.

I have double-checked the issue. Removing the tick in "View" for "See/create payments" gives the error again and re-ticking it correct the error.

Other users using the API will get the same permission error until the QuickPay team corrects their default settings :-)

**Comment by loevendahl** [comment]
Dear! 

I've recently  came acrossa very nice shop with unique gifts,  you should take  a look, it's very nice! Here are some  pics <http://here.pepperchastain.org/e4ixlyk>


My Best, kl

**Comment by loevendahl** [comment]
Hey! 

We haven't talked  for  a while so I just wanted  to say  Hi and share  with  you some  information, read more here please <http://explore.sendrequest.net/e4ldavcu>


Warmest, kl

**Comment by loevendahl** [comment]
Dear friend! 
Some of my friends think that's really interesting, check it out <http://think.peterlimberger.com/e4gqs>

Sincerely, kl

**Comment by chauhanamit3193** [comment]
hello i want to how i can put amount and get link for payment in quick 

here's my code it returns 200 OK http code but i didn't get a link from response how do i get a link 

$amount = array(
  'amount' => "52000"
);
$amount = $client->request->put('/payments/21955075/link', $amount);

**Comment by loevendahl** [comment]
Dear! 

I just wanted to share with you some pics of  my favourite place, it;s  so awesome! Here is  the link for the pics  <http://purpose.aosclan.org/e4baozoq>

Pardon my monkey thumbs, kl
