### ISSUE TITLE
Error with CURLOPT_SSL_VERIFYPEER

### ISSUE THREAD

**Issue by JensKirk** [QuickPay/quickpay-php-client#13]
Hi

By turning...

CURLOPT_SSL_VERIFYPEER => true

to...

CURLOPT_SSL_VERIFYPEER => false

I got the authenticate function to work.

Perhaps you should make it an option in the start of the source code so others do not get the same error?

The user Søren Thing explained to me that it was because I was missing a certificate on my server. I have not fixed this yet.

**Comment by ta** [comment]
You should always verify peer when working in a production environment - the internet will tell you why :)

Please see http://curl.haxx.se/docs/sslcerts.html - I'm a afraid that we are not going to make it easier to disable verify peer. I hope you understand our position.

**Comment by JensKirk** [comment]
:-)
