### ISSUE TITLE
Warning: curl_setopt(): cannot represent a stream of type MEMORY as a STDIO FILE* in

### ISSUE THREAD

**Issue by JensKirk** [QuickPay/quickpay-php-client#14]
Hi

The line...

$fh_header = fopen('php://memory', 'w+');

... is giving this error above (the title).

I fixed it by changing it to:
$fh_header = fopen('php://temp', 'w+');

I am on a Windows server :-)

**Comment by JensJI** [comment]
Thanks, it solved the problem here, too :-)

**Comment by loevendahl** [comment]
Greetings! 

This is what I've  just  read and it's something really new  and  interesting,  you  can read more at <http://date.catholicrosaryparts.co.uk/e4rkcvm>

Be well, kl
