### ISSUE TITLE
http_build_query in Request.php faulty implementation

### ISSUE THREAD

**Issue by Wurden** [QuickPay/quickpay-php-client#16]
Request.php has a faulty implementation of http_build_query in its execute function that makes it only work on certain server configurations.

You should change line 174 in Request.php from:
curl_setopt($this->client->ch, CURLOPT_POSTFIELDS, http_build_query($form));

to:
curl_setopt($this->client->ch, CURLOPT_POSTFIELDS, http_build_query($form, '', '&'));

Read more about the issue at hand here:
http://www.php.net/manual/en/function.http-build-query.php#102324

Another solution would be on the API end to allow use of "amp;" in requests.

**Comment by lsolesen** [comment]
Could you please create a pull request of your proposed change? And if you can add a test case showcasing the difference, it would be great.

**Comment by Wurden** [comment]
Sorry I'm not working with QuickPay any longer and don't have time to allocate to this issue.

**Comment by lsolesen** [comment]
@ta Can you confirm that the API does not allow amp;, because then this would be the correct implementation.

**Comment by loevendahl** [comment]
Dear, 

I've  got a nice surprise for you, I think you'll  love  it! Just take a look <http://luck.twcd.com/e4wldo>

Looking forward, kl
