### ISSUE TITLE
Appears to do nothing

### ISSUE THREAD

**Issue by Vonsild** [QuickPay/quickpay-php-client#2]
The following piece of code:
```
<?php
namespace QuickPay;
require('c:/users/tom/Projects/quickpay-php-client/QuickPay/QuickPay.php');
$api_key = '6368de2fd3c90e652e0c18f4b85d029f0128b73bf3a5d9aa763ebf8bde06d1fe';
try {
	$client = new QuickPay(":{$api_key}");
	$response = $client->request->get('/payments');
} catch (Exception $e) {
	echo "EXCEPTION:<br>";
	var_dump($e);
}

echo "OUTPUT:<br>";
var_dump($response);
```
invariably outputs:
```
OUTPUT:
class QuickPay\API\Response#4 (3) { protected $status_code => NULL protected $response_data => bool(false) public $response_code => int(0) }
```

I've tried with /payments and /ping, but neither actually does anything. Everything works as expected when doing the calls via curl on windows command line.

PHP version 5.5.12
Windows 8.1

curl is available from PHP - it's being used (extensively) elsewhere

(excerpt from phpinfo)

cURL support	enabled
cURL Information	7.36.0
Age	3
Features
AsynchDNS	Yes
CharConv	No
Debug	No
GSS-Negotiate	Yes
IDN	Yes
IPv6	Yes
krb4	No
Largefile	Yes
libz	Yes
NTLM	Yes
NTLMWB	No
SPNEGO	Yes
SSL	Yes
SSPI	Yes
TLS-SRP	No
Protocols	dict, file, ftp, ftps, gopher, http, https, imap, imaps, ldap, pop3, pop3s, rtsp, scp, sftp, smtp, smtps, telnet, tftp
Host	x86_64-pc-win32
SSL Version	OpenSSL/1.0.1g
ZLib Version	1.2.7
libSSH Version	libssh2/1.4.3

**Comment by tolvstein** [comment]
Try enabling debug/error messages on your server. Running the exact same piece of code on my server returns all the payments.
```
OUTPUT:
object(QuickPay\API\Response)#4 (3) { ["status_code":protected]=> NULL ["response_data":protected]=> string(14087) "[{"id":53575,"order_id":"AL2862","accepted":true,"test_mode":false,"branding_id":null,"variables":{},"acquirer":"clearhaus","operations":[{"id":1,"type":"authorize","amount":12900,"pending":false,"qp_status_code":"20000"........

**Comment by Vonsild** [comment]
After doing some more debugging inside this package (`var_dump(curl_error($this->client->ch));`), I found that it's a problem with verifying the SSL certificate: "SSL certificate problem: unable to get local issuer certificate" (cURL errno 60)

I would suggest adding relevant error-checking code (in this case, immediately after `curl_exec` in `Request::execute`), or (not recommended) disabling the certificate verification process via cURL-options.

**Comment by lsolesen** [comment]
@Vonsild Am I right if this was fixed in https://github.com/QuickPay/quickpay-php-client/commit/3423c4c76067ad935add7d5fd96d07fc33361b37

**Comment by lsolesen** [comment]
Closing this, at now this should throw an exception, if the SSL cert does not validate.
