### ISSUE TITLE
Documentation bug

### ISSUE THREAD

**Issue by Vonsild** [QuickPay/quickpay-php-client#3]
In the "Handling the response" section, the examples given use 
`$response = $client->get('/payments');` 
which is wrong, since the $client has no `get` method - it SHOULD be 
`$response = $client->request->get('/payments');`

**Comment by tolvstein** [comment]
True, thats a typo. I will make sure to update this.

**Comment by ta** [comment]
Fix merged in (PR https://github.com/QuickPay/quickpay-php-client/pull/4) - thanks for reporting
