### ISSUE TITLE
Tag a release 0.1.0

### ISSUE THREAD

**Issue by lsolesen** [QuickPay/quickpay-php-client#33]
I want to tag release 0.1.0.

Then I want to address a couple of PSR2 standard issues. This is the ruleset, we are using right now.

https://github.com/QuickPay/quickpay-php-client/blob/master/ruleset.xml

At least I want to tackle PSR1.Files.SideEffects.FoundWithSymbols which basically means I will remove require_once from the api-files. That, I think, is necessary for the library to be easy to use for seasoned developers - so they can decide for themselves how to include files (a lot of people will probably take advantage of the composer integration). This might break bc-compability for people NOT taking advantage of proper autoloaders.

Then we could discuss: PSR1.Methods.CamelCapsMethodName.NotCamelCaps. I would prefer that we stayed with PSR2 standards all the way through and also tackled this. However, that will make everyone using the library having to change their code to reflect these changes. This, however, will også bring the standards up to par with the big PHP-libraries. However, it would be easier to change now, than when the library grows old.

@ta What is your call on these two?

When both are tackled, I would like to release 1.0.0 of the library. Or maybe 10.0.0 which would follow the QuickPay api version number. @ta What is your call on this?

**Comment by ta** [comment]
@lsolesen I'm very much pro leaning against (defacto) standards, and I agree that it is better to make possibly breaking changes sooner than later - using tagging/versioning. WRT versioning, IMO 1.0.0 is fine since we are not modelling the entire API (but just parsing json in to arrays/objects).

**Comment by lsolesen** [comment]
Cool. I will tag a 0.1.0 release soon. Then I will refactor to follow PSR2
standards in a pull request for you to review.
Den 15/04/2016 11.02 skrev "Tonni Tølbøll Lund Aagesen" <
notifications@github.com>:
