### ISSUE TITLE
Capture from orderid

### ISSUE THREAD

**Issue by ATouhou** [QuickPay/quickpay-php-client#46]
Hello.
I can't seem to find any reference in your API Documentations on how to send a capture request to a given orderid.

Please do elaborate ASAP

**Comment by mortenhartvig** [comment]
A guess would be, that you can search after the transaction id by reference, and then capture it. Typically the application should already know the id when a "purchase" is made.

**Comment by ATouhou** [comment]
Is there not any documentation available? 
In the current API class we got things like 

$payments = $client->request->get('/payments');

$payments = $client->request->post('/payments', $form);


is there not any function for "cancel/refund" & capture?
If so I need to know how to use these :-) 

This would be for managing orders in a system, so that refunding would become easier, and abide by danish legislation by only capturing when having shipped the product.

**Comment by Sydgren** [comment]
I have no idea which system you're using, but I'm working on a Laravel 5 package for QuickPay, which should make handling orders a bit easier.

**Comment by twarberg** [comment]
@ATouhou Please see https://learn.quickpay.net/tech-talk/api/services/?scope=merchant#payments
