### ISSUE TITLE
Problem on case sensitive OS

### ISSUE THREAD

**Issue by Vonsild** [QuickPay/quickpay-php-client#5]
Using linux or other case sensitive operating systems is problematic.
QuickPay.php has a number of requires:
```
require_once( 'api/constants.php' );
require_once( 'api/exception.php' );
require_once( 'api/client.php' );
require_once( 'api/request.php' );
require_once( 'api/response.php' );
```

but those files actually have capital first letters, causing the requires to fail.

**Comment by SiliconMind** [comment]
See [my pull request](https://github.com/QuickPay/quickpay-php-client/pull/7) solves the problem and allows you to use proper autoloading or require files manually.

**Comment by ta** [comment]
Should be fixed in https://github.com/QuickPay/quickpay-php-client/commit/a6168e9e28d6d05f511a841b5d787d5d52defcfd - closing this issue,
