### ISSUE TITLE
callback url error

### ISSUE THREAD

**Issue by mohamedzajith** [QuickPay/quickpay-php-client#50]
Failed - The callback service will try to deliver its message up to 24 times, with gradually increasing delays between each try
HTTP Status kode: 405 
URL: http://kitab.dk/zajith

http://kitab.dk/zajith in this url is GET Methode
( api User )

**Comment by ta** [comment]
The callback will always be send as a HTTP POST request.

This does not seem to be related to the PHP client. I'm closing this issue - please reach out to via email https://www.quickpay.net/about with updates if any.
