### ISSUE TITLE
http_build_query and invalid basket

### ISSUE THREAD

**Issue by RBech** [QuickPay/quickpay-php-client#51]
Using the code provided here https://kopy.io/p43cq#387KIDk5r4HH51 I'm trying to create a payment with the basket information supplied, however this results in {"message":"Validation error","errors":{"basket":["is invalid"]},"error_code":null} despite the supplying all the information needed according to the documentation.

I think the culprit may be http_build_query but I'm not sure what workaround would be needed, if I use the same data and perform a json_encoded request without using the php-client things are working as expected.

**Comment by lsolesen** [comment]
Could you please supply the json encode code your are testing with also, so
I can compare the two when debugging?

Den tir. 25. apr. 2017 15.08 skrev Tonni Tølbøll Lund Aagesen <
notifications@github.com>:

**Comment by jkhwsd** [comment]
I have the same problem.

Using `http_build_query` on my data results in the following (replaced `[`, `]` and added linebreak for readability): 

    currency=DKK&
    order_id=test&
    basket[0][qty]=1&
    basket[0][item_no]=0001&
    basket[0][item_name]=test1&
    basket[0][item_price]=12345&
    basket[0][vat_rate]=0.25 
    basket[1][qty]=1&
    basket[1][item_no]=0002&
    basket[1][item_name]=test2&
    basket[1][item_price]=98765&
    basket[1][vat_rate]=0.25 

Those `[0]` and `[1]` are supposed to be `[]` or else the basket is invalid. 
If you were to put this in to an array (avoiding nested arrays) like this `$params['basket[][qty]'] = 1` which would work for a single item but the next item would override the previous since they have the same key.

**Comment by lsolesen** [comment]
Please supply exact code used, so I can debug it?

**Comment by jkhwsd** [comment]
Something like this:

    $basket = [];
    foreach ($orderItems as $orderItem) {
        $basket[] = [
            'qty' => $orderItem->quantity,
            'item_no' => $orderItem->id,
            'item_name' => $orderItem->title,
            'item_price' => $orderItem->amount,
            'vat_rate' => 0.25,
        ];
    }
    $form = [
        'currency' => 'DKK',
        'order_id' => $orderId,
        'basket' => $basket,
    ];
    $payment = $client->request->post('/payments', $form);

**Comment by lsolesen** [comment]
Could you please try to add this method https://github.com/QuickPay/quickpay-php-client/pull/54/files#diff-1a98bf2e113e437e34e01b15690a1005R103 to the Request.php and change the http_build_query() used in execute() to that method to see whether it fixes the problem?

**Comment by lsolesen** [comment]
or this alternative: 

```
function handleArray($query) {
    $query = http_build_query($query);
    $query = preg_replace('/%5B[0-9]+%5D/simU', '%5B%5D', $query);
    return $query;
}
```

**Comment by jkhwsd** [comment]
I tried your alternative, and it seems to work. 

I used it to the execute function line 163.

**Comment by lsolesen** [comment]
Which one did you try?

Den man. 22. maj 2017 08.41 skrev jkhwsd <notifications@github.com>:

**Comment by jkhwsd** [comment]
I used this one

    function handleArray($query) {
        $query = http_build_query($query);
        $query = preg_replace('/%5B[0-9]+%5D/simU', '%5B%5D', $query);
        return $query;
    }

I was wondering if all those pattern modifiers are necessary? The caseless (`i`) seems fine but the rest seems needless.

**Comment by jkhwsd** [comment]
Will there be released a new version with the error fixed?

**Comment by lsolesen** [comment]
Ah. Yeah. I have to look into this. Sorry about the delay.

Den fre. 30. jun. 2017 10.49 AM skrev jkhwsd <notifications@github.com>:

**Comment by lsolesen** [comment]
@jkhwsd and @RBech Could you please review this pull request to see whether it fixes the issue properly? https://github.com/QuickPay/quickpay-php-client/pull/54

**Comment by jkhwsd** [comment]
Looks good to me.
