### ISSUE TITLE
Support additional headers in requests

### ISSUE THREAD

**Issue by lauer** [QuickPay/quickpay-php-client#56]
This is specially nice, when a special CallBack url is needed, when testing.

A solution was started in #17, but never merged and completed. 

Pull request will follow

**Comment by AndreasHerss** [comment]
Can't believe this isn't supported... :(

**Comment by Sthing** [comment]
Thank you for the PR. Included in https://github.com/QuickPay/quickpay-php-client/releases/tag/1.1.0
