### ISSUE TITLE
How to set callback and cancel url?

### ISSUE THREAD

**Issue by devghor** [QuickPay/quickpay-php-client#64]
After authorizing the payment I want to redirect a customer to my website. If the customer cancels a payment I want to redirect him to another URL. Is there any way accomplish this task?

**Comment by martinstougaard** [comment]
@devghor when you PUT /link,
There you can define cancel, continue and callback url

**Comment by devghor** [comment]
Can you explain by code?

**Comment by martinstougaard** [comment]
Have a look at this example

https://learn.quickpay.net/tech-talk/payments/link/#quickpay-link

Where amount I set, you can add the cancel/continue/callback urls

**Comment by devghor** [comment]
@martinstougaard Is this the correct?

$link = $client->request->put($endpoint, [
        'amount' => 100, 
        'cancel' => $cancel_url,
        'continue=> $contnue_url
]);

**Comment by martinstougaard** [comment]
It should be `cancelurl` and `callbackurl`

**Comment by devghor** [comment]
cancelurl is working. But after successfully complete the payment it not redirected to calbackurl.

**Comment by benee** [comment]
@devghor 

```
$link = $client->request->put($endpoint, [
'amount' => 100,
'cancel_url' => $cancelurl,
'continue_url' => $continueurl,
'callback_url' => $callbackurl
]);
```

parameter | description 
-- | --
continue_url | Url that cardholder is redirected to after authorize
cancel_url | Url that cardholder is redirected to after cancelation
callback_url | Endpoint for async callback

You can see all the available parameters on https://learn.quickpay.net/tech-talk/api/services/#PUT-payments--id-link---format-

I will close this issue for now, as it is not an issue with the client. 

If you have further questions you are always welcome to send a mail to support@quickpay.net
